RENAME TABLE aanmeldingen TO stem_aanmeldingen
RENAME TABLE berichten TO stem_berichten
RENAME TABLE bestellingen TO stem_bestellingen
RENAME TABLE bestellingen_lis TO stem_bestellingen_lis
RENAME TABLE bestellingen_producten TO stem_bestellingen_producten
RENAME TABLE cisession TO stem_cisession
RENAME TABLE docenten TO stem_docenten
RENAME TABLE gebruikers TO stem_gebruikers
RENAME TABLE gegevens TO stem_gegevens
RENAME TABLE groepen TO stem_groepen
RENAME TABLE groepen_lessen TO stem_groepen_lessen
RENAME TABLE huiswerk TO stem_huiswerk
RENAME TABLE individuen_lessen TO stem_individuen_lessen
RENAME TABLE lessen TO stem_lessen
RENAME TABLE media TO stem_media
RENAME TABLE media_connecties TO stem_media_connecties
RENAME TABLE nieuws TO stem_nieuws
RENAME TABLE opendagen TO stem_opendagen
RENAME TABLE paginas TO stem_paginas
RENAME TABLE praktijkdagen TO stem_praktijkdagen
RENAME TABLE praktijkdagen_lessen TO stem_praktijkdagen_lessen
RENAME TABLE producten TO stem_producten
RENAME TABLE reacties TO stem_reacties
RENAME TABLE resultaten TO stem_resultaten
RENAME TABLE uitnodigingen TO stem_uitnodigingen
RENAME TABLE vragen TO stem_vragen
RENAME TABLE workshops TO stem_workshops
RENAME TABLE workshop_producten TO stem_workshop_producten