<h1>Extra les <?php echo $actie ?></h1>
<div id="toevoegen_wijzigen" class="formulier">
    <form method="post" action="<?php if($actie == 'toevoegen') echo base_url('cms/lessen/extra_toevoegen/'.$item_ID); else echo base_url('cms/lessen/extra_wijzigen/'.$item_ID. '/'. $les_ID); ?>">
        <p><label for="item_titel">Titel *</label><input type="text" name="item_titel" id="item_titel" value="<?php echo $item_titel ?>" /><span class="feedback"><?php echo $item_titel_feedback ?></span></p>
        <p><label for="item_beschrijving">Beschrijving *</label><textarea name="item_beschrijving" id="item_beschrijving" class="opmaak"><?php echo $item_beschrijving ?></textarea><span class="feedback"><?php echo $item_beschrijving_feedback ?></span></p>
        <p><label for="item_datum_dag">Datum *</label><input type="text" name="item_datum_dag" id="item_datum_dag" class="datum_smal" value="<?php echo $item_datum_dag ?>" /><input type="text" name="item_datum_maand" id="item_datum_maand" class="datum_smal" value="<?php echo $item_datum_maand ?>" /><input type="text" name="item_datum_jaar" id="item_datum_jaar" class="datum_breed" value="<?php echo $item_datum_jaar ?>" /><span class="feedback"><?php echo $item_datum_feedback ?></span></p>
        <p><label for="item_tijd_uren">Begintijd *</label><input type="text" name="item_tijd_uren" id="item_tijd_uren" class="datum_smal" value="<?php echo $item_tijd_uren ?>" /><input type="text" name="item_tijd_minuten" id="item_tijd_minuten" class="datum_smal" value="<?php echo $item_tijd_minuten ?>" /><span class="feedback"><?php echo $item_tijd_feedback ?></span></p>
        <p><label for="item_eindtijd_uren">Eindtijd *</label><input type="text" name="item_eindtijd_uren" id="item_eindtijd_uren" class="datum_smal" value="<?php echo $item_eindtijd_uren ?>" /><input type="text" name="item_eindtijd_minuten" id="item_eindtijd_minuten" class="datum_smal" value="<?php echo $item_eindtijd_minuten ?>" /><span class="feedback"><?php echo $item_eindtijd_feedback ?></span></p>
        <p><label for="item_adres">Adres *</label><input type="text" name="item_adres" id="item_adres" value="<?php echo $item_adres ?>" /><span class="feedback"><?php echo $item_adres_feedback ?></span></p>
        <p><label for="item_postcode">Postcode *</label><input type="text" name="item_postcode" id="item_postcode" value="<?php echo $item_postcode ?>" /><span class="feedback"><?php echo $item_postcode_feedback ?></span></p>
        <p><label for="item_plaats">Plaats *</label><input type="text" name="item_plaats" id="item_plaats" value="<?php echo $item_plaats ?>" /><span class="feedback"><?php echo $item_plaats_feedback ?></span></p>
        <p class="submit"><input type="submit" value="Les <?php echo $actie ?>" /> <a href="<?php echo base_url('cms/lessen/'.$item_ID) ?>" title="Annuleren">Annuleren</a> <?php if($actie == 'wijzigen'): ?><a href="<?php echo base_url('cms/lessen/verwijderen/'.$item_ID) ?>" title="Verwijderen">Verwijderen</a><?php endif; ?></p>
    </form>
</div>